prepare:
  intervals: [1, 4] #[1, 4, 8, 16, 32] #[1, 4] # ! the problem for baking with last frame would be the lenght not divied by 4
  depth_mode: uni
  # for query cotracker
  num_long_term_d: 15000 # 20000
  chunk_long_term_d: 12000 # ! super important
  num_long_term_s: 8192
  chunk_long_term_s: 8192
  epi_th_long_term: 300 # ! fps sensitive
  long_track_keyframe_interval: 32 # ! fps sensitive
  long_track_dyn_subsample: 4
  # sky
  dummy_sky_seg: True # not segment out sky
  dense_interval: True
