dataset_mode: iphone

spatial_unit_meter: 0.01 # ? 0.025 # 0.04 # when considering the re-size! surfelwarp use 2.5cm

t_subsample: 1
temporal_diff_shift: [2, 8, 16]
temporal_diff_weight: [0.6, 0.4, 0.3]

max_sph_order: 1
pix_subsample: 1
flow_interval: [1] #[1, 4, 8, 16] #[1, 4, 8, 16, 32] #[1, 4]
semantic_th_quantile: 0.9 #0.95 #0.95

use_short_flow: False

recomp_dyn_mask_consider_inside_dyn: True

mask_prop_steps: 6
epi_error_th_factor: 400.0 # default
depth_boundary_th: 100.0

mask_consider_track: True
mask_init_erode: 3

normal_patch_size: 3
normal_nn_dist_th: 0.03
normal_nn_min_cnt: 3

static_scf:
  total_steps: 4000
  lr_cam_f: 0.0003 # the ba function will auto set 0.0 for gt_cam
  fov_fallback: 40.0
  fov_search_min_interval: 2
  fov_interval_single: False

static_gs:
  n_init: 10000
  total_steps: 4000
  optim_cam_after_steps: 3000

  lambda_rgb: 1.0
  lambda_dep: 0.5

dyn_scf:
  lr_p: 0.1
  lr_q: 0.1
  max_node_num: 20000
  topo_k: 10

  # stage4_steps: 0
  grow_node_by_coverage: False

  topo_curve_dist_top_k: 7
  topo_curve_dist_sample_T: 80

  sigma_max_ratio: 1.0 #0.6 #1.0
  sigma_init_ratio: 0.1

  # lambda_local_coord: 0.0
  # lambda_metric_len: 1.0
  lambda_xyz_acc: 0.1

  topo_th_ratio: 5.0 # 10 ! important
  vel_jitter_ratio: 3.0
  min_valid_cnt_ratio: 0.1

  mlevel_list: [1, 8, 16]
  mlevel_k_list: [16, 8, 8]
  mlevel_w_list: [0.4, 0.3, 0.3]
  mlevel_resample_steps: 32

  viz_interval: 100

dyn_gs:
  topo_th_ratio: 3.0

  n_init: 30000 # 1,3
  init_key_frames: 10 #20 # 10
  leaf_local_flag: True #False
  model_pixel_subsample: 2

  total_steps: 8000
  optim_cam_after_steps: 5000
  skinning_corr_start_steps: 6000

  lambda_rgb: 1.0
  lambda_dep: 0.01 #0.05 # ! looks small is better!
  lambda_normal: 0.2
  geo_reg_start_steps: 1000

  lambda_acc_rot_reg: 1.0
  lambda_acc_xyz_reg: 1.0
  lambda_arap_coord: 3.0 #3.0
  lambda_arap_len: 3.0 #3.0

  d_ctrl:
    # densify_max_grad: 0.00008
    # node_densify_max_grad: 0.00008
    densify_max_grad: 0.0002
    node_densify_max_grad: 0.0004

    # prune_opacity_th: 0.01
    # node_prune_opacity_th: 0.01
    # ! stricter
    prune_opacity_th: 0.05
    node_prune_opacity_th: 0.05
    reset_opacity: 0.01
