NUM_SEMANTIC_CHANNELS: 32 #16
Head:
  sam2:
    enable: False
    path: sam2_feats.pth
    head_type: mlp
    encoder: []
    decoder: [32, 64, 128, 256]

  internvideo:
    enable: False
    path: internvideo_feats.pth
    head_type: mlp
    encoder: []
    decoder: [32, 64, 128, 256, 512, 1024, 1408]

  langseg:
    enable: True
    path: sam_embeddings
    head_type: mlp
    encoder: []
    decoder: [32, 64, 128, 256]